# Generated by Django 5.1.1 on 2024-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_property_cat_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('carpet_area', models.CharField(max_length=100)),
                ('date_listed', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
