# Generated by Django 5.1.1 on 2024-11-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_property_rent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property_rent',
            old_name='status',
            new_name='available',
        ),
        migrations.AddField(
            model_name='property_rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
