# Generated by Django 5.1.1 on 2024-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_rent',
            name='deposite_amount',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10, null=True),
        ),
    ]
