# Generated by Django 5.1.5 on 2025-01-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pro_cat',
            field=models.ForeignKey(default='Flat', on_delete=django.db.models.deletion.PROTECT, to='myapp.property_cat'),
        ),
    ]
