# Generated by Django 5.1.5 on 2025-01-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_property_pro_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pro_cat',
        ),
    ]
