# Generated by Django 5.1.1 on 2024-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
    ]
