# Generated by Django 5.1.5 on 2025-01-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_property_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='qty',
        ),
    ]
